---
title: Your awesome title
timezone: UTC
collections:
  advisory-board:
    title: Advisory Board
    output: true
  board-of-overseers:
    title: Board of Overseers
    output: true
  iamf-details:
    title: IAMF Details
    output: true
  posts:
    title: Posts
    output: true
  team:
    title: Team
    output: true
  uploads:
    title: Uploads
    output: true
email: your-email@domain.com
description: Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.
baseurl: ''
url: http://0.0.0.0:4000
twitter_username: jekyllrb
github_username: jekyll
markdown: kramdown
defaults:
  scope:
    path: "team"
    type: "team"
  values:
    designation: "President"
    photo: "/uploads/bender.png"
    profile_url: "https://en.wikipedia.org/wiki/Walter_Bender"
