---
title: Your awesome title
timezone: UTC
collections:
  events:
    title: Events
    output: true
  iamf-details:
    title: IAMF Details
    output: true
  posts:
    title: Posts
    output: true
  team:
    title: Team
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: team
  values:
    title: Team Member
    designation: 
    photo: 
    profile_url: 
- scope:
    path: ''
    type: advisory-board
  values:
    title: 
    designation: 
    company: 
    location: 
- scope:
    path: ''
    type: board-of-overseers
  values:
    title: 
    designation: 
    company: 
    location: 
- scope:
    path: ''
    type: events
  values:
    title: 
    image: 
    venue: 
    date: 
    event_url: 
email: your-email@domain.com
description: Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.
baseurl: ''
url: http://0.0.0.0:4000
twitter_username: jekyllrb
github_username: jekyll
markdown: kramdown
